version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cookbook_postgres
    restart: always
    environment:
      POSTGRES_USER: cookbook_user
      POSTGRES_PASSWORD: cookbook_password
      POSTGRES_DB: cookbook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cookbook_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0 # Use a specific, compatible version
    container_name: cookbook_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disabling security for local development ONLY
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - cookbook_network

  redis:
    image: redis:7
    container_name: cookbook_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cookbook_network

volumes:
  postgres_data:
  es_data:
  redis_data:

networks:
  cookbook_network:
    driver: bridge